# Tighten on app code; relax on tests/tools
exclude_dirs:
  - tests
  - docs
  - .venv
  - venv
skips:
# assert used (ok in tests)
  - B101 
  # paramiko calls (not used)
  - B601 
  # subprocess without shell=True false positives
  - B603  
  # subprocess module import warning
  - B404 
  # subprocess shell=True (we don't use shell=True in app)
  - B602  
