title = "AV-SAFE — allowlist for doc placeholders (API + Corpus)"

[allowlist]
description = "Ignore placeholder Authorization/Idempotency-Key lines in documentation; scan everything else."
paths = [
  '''(?i)^docs/api\.md$''',
  '''(?i)^docs/corpus\.md$'''
]
regexes = [
  '''^Authorization:\s*Bearer\s*(<token>|&lt;token&gt;)(\s*#.*)?$''',
  '''^Idempotency-Key:\s*(<uuid-v4>)(\s*#.*)?$'''
]
