# .pre-commit-config.yaml
repos:
  # Core hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Python formatting (Black)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Linting (Ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: []

  # Typos
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["-L", "teh,ba,nd"]  # add domain words here
        exclude: |
          (?x)(
            ^docs/.*\.md$
          )

  # Secret scanning (local dev)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets              # must remain this id
        name: detect-non-pertinent      # friendly label shown in output
        args:
          - --baseline
          - .non-pertinent.baseline
        # Match CI docs exclusions to reduce noise locally
        exclude: |
          (?x)(
            ^docs/api\.md$|
            ^docs/corpus\.md$|
            ^docs/quickstart\.md$
          )
