# .ruff.toml — works with Ruff >=0.4
target-version = "py311"
line-length = 100

[lint]
# Enable: pycodestyle(E), pyflakes(F), import sort(I), bugbear(B), pyupgrade(UP), bandit(S)
select = ["E", "F", "I", "B", "UP", "S"]
ignore = [
  "E203",  # slice spacing (Black compatibility)
  "E266",  # too many leading '#' for block comment
]

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]                 # allow re-exports
"cloud/api_app.py" = ["B008"]               # FastAPI default factories pattern
"tools/*" = ["S301","S403","S404","S603"]   # Bandit relaxations for dev helpers
"tests/**.py" = ["S101","B011","B018","B905"]  # asserts etc. ok in tests
