site_name: AV-SAFE Toolkit
site_description: Privacy-preserving audiovisual metrology & historico-forensic corpus
theme:
  name: material
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API: api.md
  - Corpus (HF-AVC): corpus.md
repo_url: https://github.com/<YOURUSER>/av-safe-toolkit
