name: AV-SAFE cloud-e2e-local

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      AUTH_MODE: dev
      DEV_TOKEN: devtoken
      LOCAL_MODE: "1"
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements.txt || true
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install fastapi mangum pydantic python-jose[cryptography] requests uvicorn jsonschema

      - name: Start local API (FastAPI)
        run: |
          nohup python -m uvicorn cloud.api_app:app --host 127.0.0.1 --port 8000 >/tmp/api.log 2>&1 &
          for i in {1..20}; do
            sleep 0.5
            curl -fsS http://127.0.0.1:8000/health && break || true
          done
          curl -fsS http://127.0.0.1:8000/health || (echo "API failed to start"; tail -n +1 /tmp/api.log; exit 1)

      - name: Generate minutes (sim) & upload locally
        run: |
          python -m avsafe_descriptors.cli.sim --minutes 2 --outfile minutes.jsonl
          gzip -c minutes.jsonl > minutes.jsonl.gz
          python tools/client_uploader.py --base http://127.0.0.1:8000 --token "$DEV_TOKEN" \
            --label "CI Case" --device DEV-CI --file minutes.jsonl.gz
          python -m cloud.local_runner --once

      - name: Assert report exists & is non-empty
        run: |
          echo "Tree:"
          ls -R local_data | sed -n '1,400p'
          REPORT=$(find local_data -type f -name 'report.html' | head -n1 || true)
          echo "Report path: $REPORT"
          test -n "$REPORT"
          test -s "$REPORT"

      - name: Validate minutes against schema
        run: |
          MIN=$(find local_data -type f -path '*/avsafe-verified/verified/*/*/minutes.jsonl' | head -n1 || true)
          echo "Minutes path: $MIN"
          test -n "$MIN"
          python -m avsafe_descriptors.cli.validate_minutes \
            --in "$MIN" \
            --schema avsafe_descriptors/hf_avc/schemas/avsafe-minute-summary.schema.json

      - name: Print API logs on success (helpful for debugging)
        if: always()
        run: |
          echo "==== /tmp/api.log ===="
          tail -n +1 /tmp/api.log || true
