# .github/workflows/lint-and-types.yml
name: lint-and-types
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install ruff==0.13.2
      - name: Ruff lint (soft)
        run: |
          echo "Running Ruff in soft mode (won't fail CI)"
          ruff --version
          # Annotate problems in the PR UI, but never fail:
          ruff check . --output-format=github --exit-zero
