name: security

on:
  push:
    branches: [ main, master, develop, "*" ]
  pull_request:
  schedule:
    - cron: "0 9 * * 1"   # Mondays 09:00 UTC
  workflow_dispatch:

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: false

jobs:
  python-vulns:
    name: Python dependency vulnerabilities (pip-audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Audit requirements files (hard fail on CVEs)
        run: |
          found=0
          if [ -f requirements.txt ]; then pip-audit -r requirements.txt || found=1; fi
          if [ -f requirements-dev.txt ]; then pip-audit -r requirements-dev.txt || found=1; fi
          # Also audit the current env in case extras are installed during CI
          pip-audit || found=1
          exit $found

  bandit:
    name: Static analysis (Bandit; medium+ severity & high confidence)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit (fail on findings)
        run: |
          bandit -q -r . \
            -x tests,venv,.venv,build,dist,local_data,node_modules \
            -ll -iii

  secrets:
    name: Secret scanning (Gitleaks; hard fail)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (fail on leaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: >-
            detect
            --no-banner
            --redact
            --verbose
            --source .
